
/**************************************************************
 *	
 *	laser, 8 bit, 11025Hz,
 *	1 channel, 6000 bytes/channel
 *	Total Size: 1 * 6000 + 4 (header) = 6044 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\dcryts3\Desktop\sounds\laser.wav
 *	Time-stamp: Tue Apr 22 20:31:22 2014
 *	
 **************************************************************/

#ifndef __LASERH__
#define __LASERH__

#define LASERFREQ 11025
#define LASERLEN 6000

extern const unsigned char laser[6000];

#endif /* __LASERH__ */
