
/**************************************************************
 *	
 *	midHorizons, 8 bit, 11025Hz,
 *	1 channel, 394695 bytes/channel
 *	Total Size: 1 * 394695 + 4 (header) = 394739 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\dcryts3\Desktop\sounds\midHorizons.wav
 *	Time-stamp: Tue Apr 22 20:31:26 2014
 *	
 **************************************************************/

#ifndef __MIDHORIZONSH__
#define __MIDHORIZONSH__

#define MIDHORIZONSFREQ 11025
#define MIDHORIZONSLEN 394695

extern const unsigned char midHorizons[394695];

#endif /* __MIDHORIZONSH__ */
