
/**************************************************************
 *	
 *	startHorizons, 8 bit, 11025Hz,
 *	1 channel, 264600 bytes/channel
 *	Total Size: 1 * 264600 + 4 (header) = 264644 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\dcryts3\Desktop\sounds\startHorizons.wav
 *	Time-stamp: Tue Apr 22 20:31:31 2014
 *	
 **************************************************************/

#ifndef __STARTHORIZONSH__
#define __STARTHORIZONSH__

#define STARTHORIZONSFREQ 11025
#define STARTHORIZONSLEN 264600

extern const unsigned char startHorizons[264600];

#endif /* __STARTHORIZONSH__ */
